version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-oci8
    container_name: php-oci8
    ports:
      - '80:80'
    depends_on:
      - memcached
  memcached:
    container_name: memcached
    image: memcached:alpine
    mem_limit: 256m
    ports:
      - "11211:11211"
    command: memcached -m 192m
